### ISSUE TITLE
CPU usage being capped

### ISSUE THREAD

**Issue by shipengcheng1230** [JuliaSIMD/Polyester.jl#28]
So I have this weird issue on a computer cluster. I logged in to the server where the master node has 20 CPUs. I installed the package and submit a job to a node with 36 CPUs:
```julia
using BenchmarkTools
using Polyester

@show Polyester.dynamic_thread_count() # shows the correct CPUs number

u = rand(10000, 10000)
v = similar(u)
function foo(u, v)
    @batch for i ∈ eachindex(u)
        v[i] = sin(cos(tan(exp(log(u[i] + 1)))))
    end
end

@btime foo($u, $v)
```

However, the CPU usage is capped at 2000%. And the benchmark results confirm that. It can match with a lower number of Julia threads but not more.

I found a solution which is `dev` this package, add `__precompile__(false)`. Then delete the compiled code folder. Resubmit the job and the CPU usages can reach any number I specified above 2000%. Then I `free` this package (back to the beginning state I guess) and no issue occur after then. 

Could it be due my specific hardware related problem, or perhaps something else? Thank you!

**Comment by chriselrod** [comment]
Ah, I think I know the problem.
```julia
julia> @macroexpand @batch for i ∈ eachindex(u)
               v[i] = sin(cos(tan(exp(log(u[i] + 1)))))
           end
quote
    #= /home/chriselrod/.julia/dev/Polyester/src/closure.jl:182 =#
    if (VectorizationBase.num_threads)() == 1
        #= /home/chriselrod/.julia/dev/Polyester/src/closure.jl:183 =#
        let
            #= /home/chriselrod/.julia/dev/Polyester/src/closure.jl:184 =#
            for i = eachindex(u)
                #= REPL[18]:2 =#
                v[i] = sin(cos(tan(exp(log(u[i] + 1)))))
            end
        end
    else
        #= /home/chriselrod/.julia/dev/Polyester/src/closure.jl:187 =#
        let
            #= /home/chriselrod/.julia/dev/Polyester/src/closure.jl:188 =#
            begin
                #= /home/chriselrod/.julia/dev/Polyester/src/closure.jl:136 =#
                var"#30###LOOP##" = eachindex(u)
                #= /home/chriselrod/.julia/dev/Polyester/src/closure.jl:137 =#
                var"#31###ITER_LENG##" = Polyester.static_length(var"#30###LOOP##")
                #= /home/chriselrod/.julia/dev/Polyester/src/closure.jl:138 =#
                var"#32###LOOP_STEP##" = (ArrayInterface.static_step)(var"#30###LOOP##")
                #= /home/chriselrod/.julia/dev/Polyester/src/closure.jl:139 =#
                var"#33###LOOPOFFSET##" = (ArrayInterface.static_first)(var"#30###LOOP##")
                begin
                    #= /home/chriselrod/.julia/dev/Polyester/src/closure.jl:163 =#
                    var"##closure##" = let
                            #= /home/chriselrod/.julia/dev/Polyester/src/closure.jl:164 =#
                            ((var"##LOOPOFFSET##", var"##LOOP_STEP##", v, u), var"##SUBSTART##"::Int, var"##SUBSTOP##"::Int)->begin
                                    $(Expr(:meta, :inline))
                                    #= /home/chriselrod/.julia/dev/Polyester/src/closure.jl:164 =#
                                    #= /home/chriselrod/.julia/dev/Polyester/src/closure.jl:165 =#
                                    var"##LOOPSTART##" = (var"##SUBSTART##" * var"##LOOP_STEP##" + var"##LOOPOFFSET##") - var"##LOOP_STEP##"
                                    #= /home/chriselrod/.julia/dev/Polyester/src/closure.jl:166 =#
                                    var"##LOOP_STOP##" = (var"##SUBSTOP##" * var"##LOOP_STEP##" + var"##LOOPOFFSET##") - var"##LOOP_STEP##"
                                    #= /home/chriselrod/.julia/dev/Polyester/src/closure.jl:167 =#
                                    begin
                                        $(Expr(:inbounds, true))
                                        local var"#38#val" = begin
                                                    #= /home/chriselrod/.julia/dev/Polyester/src/closure.jl:168 =#
                                                    for i = var"##LOOPSTART##":var"##LOOP_STEP##":var"##LOOP_STOP##"
                                                        #= REPL[18]:2 =#
                                                        v[i] = sin(cos(tan(exp(log(u[i] + 1)))))
                                                    end
                                                end
                                        $(Expr(:inbounds, :pop))
                                        var"#38#val"
                                    end
                                    #= /home/chriselrod/.julia/dev/Polyester/src/closure.jl:170 =#
                                    nothing
                                end
                        end
                end
                (Polyester.batch)(var"##closure##", (var"#31###ITER_LENG##", Polyester.min(var"#31###ITER_LENG##", (min)((VectorizationBase.num_threads)(), (VectorizationBase.num_cores)()))), var"#33###LOOPOFFSET##", var"#32###LOOP_STEP##", v, u)
            end
        end
    end
end
```
VectorizationBase probably didn't update `VectorizationBase.num_cores`, because it's currently only updating values if the CPU name changes.
But of course, two CPUs can have the same `Sys.CPU_NAME` but different numbers of cores and different cache sizes.
I'll try fixing that.

Also, I assume your real loop looks very different, but for `foo`, `LoopVectorization.@tturbo` should be much faster than `Polyester.@batch`.

**Comment by chriselrod** [comment]
Should be fixed by https://github.com/JuliaSIMD/VectorizationBase.jl/commit/70ccca8062017f83f08903c528221a6c2db9a9ff

**Comment by shipengcheng1230** [comment]
> Can you check if both of those nodes have the same Sys.CPU_NAME?

The names are different indeed, "Ivybridge" vs "cascadelake".

I tried with VectorizationBase#master but the problem still exists.

**Comment by chriselrod** [comment]
> The names are different indeed, "Ivybridge" vs "cascadelake".

What I noted would've only been a problem if the names are the same.
If checks if the names are different to opt out of finer grained checks for things that need to be corrected.

> So the problem looks like in the `VectorizationBase.num_threads()`, is it because of the `StaticInt` and it can only accommodate to a smaller number but not a bigger one:

Oops, fixed on master.

**Comment by shipengcheng1230** [comment]
I have to manually call `redefine_num_threads`,

```julia
@show Threads.nthreads()

using VectorizationBase
@show VectorizationBase.num_cores()
@show VectorizationBase.num_threads()
@show VectorizationBase.sys_threads()

@show "\n"
VectorizationBase.redefine_num_threads()
@show VectorizationBase.num_threads()

using Polyester
@show Polyester.dynamic_thread_count()
```

shows:

```
Threads.nthreads() = 36
VectorizationBase.num_cores() = static(36)
VectorizationBase.num_threads() = static(20)
VectorizationBase.sys_threads() = static(36)
"\n" = "\n"
VectorizationBase.num_threads() = static(36)
Polyester.dynamic_thread_count() = 36
```

Could it be the early return during `__init__`?

**Comment by chriselrod** [comment]
> Could it be the early return during `__init__`?

That only makes it return during precompilation.
I think `__init__` was calling the old method for `sys_threads` rather than the new one, so I'd either need to use `invokelatest` or `Sys.CPU_THREADS`. I went with the latter. Can you try again?

**Comment by shipengcheng1230** [comment]
Works great! Huge thanks!

**Comment by chriselrod** [comment]
Great! A new release [will be tagged shortly](https://github.com/JuliaRegistries/General/pull/37715).
