### ISSUE TITLE
UndefVarError in 0.4.0

### ISSUE THREAD

**Issue by SkyWorld117** [JuliaSIMD/Polyester.jl#42]
The following code worked well in 0.3.9 but not in 0.4.0. 

```julia
Epoch 1
[ERROR: LoadError: UndefVarError: #61#msg not defined
Stacktrace:
 [1] macro expansion
   @ C:\Users\89639\.julia\packages\Polyester\uMMPU\src\closure.jl:225 [inlined]
 [2] activate(input_data::Vector{Float32}, input::Vector{Float32}, output::Vector{Float32}, weights::Matrix{Float64}, voltage::Vector{Float32}, M::Vector{Float32}, Pᵢ::Matrix{Float32}, table::Matrix{Int64}, label::Int64)
   @ Main C:\Users\89639\Documents\Projects\DianoiaGSNN\exp\m2.jl:56
 [3] macro expansion
   @ C:\Users\89639\Documents\Projects\DianoiaGSNN\exp\m2.jl:129 [inlined]
 [4] macro expansion
   @ .\timing.jl:210 [inlined]
 [5] main()
   @ Main C:\Users\89639\Documents\Projects\DianoiaGSNN\exp\m2.jl:119
 [6] top-level scope
   @ C:\Users\89639\Documents\Projects\DianoiaGSNN\exp\m2.jl:148
in expression starting at C:\Users\89639\Documents\Projects\DianoiaGSNN\exp\m2.jl:148
```
```julia
using Polyester, LoopVectorization, MLDatasets, VectorizedRNG

function flatten(dataset::AbstractArray, batch_dim::Int64)
    dims = ndims(dataset)
    len = 1
    for i in 1:dims
        if i!=batch_dim
            len *= size(dataset, i)
        end
    end
    input_data = zeros(Float32, len, size(dataset, batch_dim))
    @batch for i in axes(dataset, batch_dim)
        input_data[:,i] = Array{Float32}(reshape(selectdim(dataset, batch_dim, i), (len,1)))
    end
    return input_data
end

function Poisson!(current_input_data::Array{Float32}, spiking_trains::Array{Float32}, x::Array{Float32})
    rand!(local_rng(), x)
    @avxt for i in 1:length(spiking_trains)
        spiking_trains[i] = ifelse(current_input_data[i]>x[i], 1.0f0, 0.0f0)
    end
end

function activate(input_data, input, output, weights, voltage, M, Pᵢ, table, label)
    T = 100
    η = 0.01
    γᵥ = 0.9 
    γₚ = 0.9
    γₘ = 0.9
    θ = 0.1
    CD = 2

    x = zeros(Float32, size(input_data))
    fire_rec = fill(-CD, size(output))

    for t in 1:T
        if (t-1)%CD == 0
            Poisson!(input_data, input, x)
        else
            @avxt input .= 0
        end
        @avxt for l in axes(weights, 1)
            s = 0.0f0
            for i in axes(weights, 2)
                Pᵢ[l,i] *= γₚ
                Pᵢ[l,i] += ifelse(input[i]!=0, 1, 0)
                weights[l,i] += η * M[l]*weights[l,i] * ifelse(input[i]!=0, 1, 0)
                s += weights[l,i] * input[i]
            end
            voltage[l] += s * ifelse(t-fire_rec[l]>CD, 1, 0)
            voltage[l] *= γᵥ
        end

        @batch for l in axes(weights, 1)
            M[l] *= γₘ
            if voltage[l]<θ && t-fire_rec[l]>CD && l==label
                voltage[l] += θ
                output[l] -= 1
            end

            if voltage[l]>θ && t-fire_rec[l]>CD
                output[l] += 1
                if l==label
                    M[l] -= 1
                    @avx for i in axes(weights, 2)
                        weights[l,i] += η * Pᵢ[l,i]*weights[l,i]
                    end
                end
                voltage[l] = 0.0f0
                fire_rec[l] = t
            end
        end
    end

    @avxt for i in 1:length(output)
        table[i, label] += output[i]
    end

    @avxt M .= 0.0f0
    @avxt Pᵢ .= 0.0f0
    @avxt voltage .= 0.0f0
    @avxt output .= 0
end

function main()
    train_x, train_y = MNIST.traindata()
    input_data = flatten(train_x, 3)
    output_data = Array{Int64}(train_y)

    input_size = 784
    layer_size = 10

    batch_size = 500
    epochs = 10

    voltage = zeros(Float32, layer_size)
    weights = rand(0.0f0:1.0f-5:sqrt(6/(input_size+layer_size)), layer_size,input_size)
    M = zeros(Float32, size(voltage))
    Pᵢ = zeros(Float32, size(weights))

    input = zeros(Float32, input_size)
    output = zeros(Float32, layer_size)

    current_input_data = zeros(Float32, size(input))
    table = zeros(Int64, layer_size,layer_size)
    rec = zeros(Int64, layer_size)

    for e in 1:epochs
        print("Epoch ", e, "\n[")

        @time begin
            for t in 1:batch_size
                index = rand(1:size(input_data)[end])
                @avxt current_input_data .= input_data[:,index]

                if t%ceil(batch_size/50)==0
                    print("=")
                end
                
                rec[output_data[index]+1] += 1
                activate(current_input_data, input, output, weights, voltage, M, Pᵢ, table, output_data[index]+1)
            end
            print("]\nTime usage: ")
        end
        
        @assert sum(isnan.(weights))==0

        println(rec)
        display(table)
        println()
        println()

        @avxt rec .= 0
        @avxt table .= 0
    end
end

main()
```

**Comment by chriselrod** [comment]
Thanks for the issue, should be fixed on Polyester 0.4.1.

**Comment by SkyWorld117** [comment]
I may have to ask to re-open this issue. It is still not working in 0.4.1. 

```julia
Epoch 1
[ERROR: LoadError: UndefVarError: maxlog not defined
Stacktrace:
 [1] macro expansion
   @ C:\Users\89639\.julia\packages\Polyester\8aJxe\src\closure.jl:236 [inlined]
 [2] activate(input_data::Vector{Float32}, input::Vector{Float32}, output::Vector{Float32}, weights::Matrix{Float64}, voltage::Vector{Float32}, M::Vector{Float32}, Pᵢ::Matrix{Float32}, table::Matrix{Int64}, label::Int64)
   @ Main C:\Users\89639\Documents\Programs\Julia\JuliaSIMD_Debug\UndefVarError.jl:55
 [3] macro expansion
   @ C:\Users\89639\Documents\Programs\Julia\JuliaSIMD_Debug\UndefVarError.jl:122 [inlined]
 [4] macro expansion
   @ .\timing.jl:210 [inlined]
 [5] main()
   @ Main C:\Users\89639\Documents\Programs\Julia\JuliaSIMD_Debug\UndefVarError.jl:112
 [6] top-level scope
   @ C:\Users\89639\Documents\Programs\Julia\JuliaSIMD_Debug\UndefVarError.jl:139
in expression starting at C:\Users\89639\Documents\Programs\Julia\JuliaSIMD_Debug\UndefVarError.jl:139
```

**Comment by chriselrod** [comment]
I fixed it locally, but as long as I still have Polyester use `PtrArray`s, I'm getting segfaults.

I suggest sticking with `Polyester@0.3` until this is fixed.

**Comment by chriselrod** [comment]
It should work now in 0.4.2.

**Comment by SkyWorld117** [comment]
> It should work now in 0.4.2.

Thank you for the fast fix, it is working fine now.
